config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("phonebook.users.urls", namespace="users")),
    path("contacts/", include("phonebook.contacts.urls", namespace="contacts")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

phonebook/contacts/urls.py
from django.urls import path

from phonebook.contacts.views import (
    AddContactView,
    ContactDetailView,
    ContactListView,
    DeleteContactView,
    DeletePhoneView,
)

app_name = "contacts"

urlpatterns = [
    path("add/", AddContactView.as_view(), name="add_contact"),
    path("", ContactListView.as_view(), name="contact_list"),
    path("<int:pk>/", ContactDetailView.as_view(), name="contact_detail"),
    path("<int:pk>/delete/", DeleteContactView.as_view(), name="delete_contact"),
    path("phone_number/<int:pk>/delete/", DeletePhoneView.as_view(), name="delete_phone_number"),
]

phonebook/users/urls.py
from django.urls import path

from phonebook.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

phonebook/common/models.py
from django.db import models
from django.utils import timezone


class BaseModel(models.Model):
    created_at = models.DateTimeField(db_index=True, default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

phonebook/contacts/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)


class CountryCode(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=5)


class PhoneNumber(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name="phone_numbers")
    country_code = models.ForeignKey(CountryCode, on_delete=models.CASCADE)
    number = models.CharField(max_length=20)

phonebook/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for phonebook.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

phonebook/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

phonebook/contacts/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import ListView

from phonebook.contacts.selectors import list_contacts, list_country_codes
from phonebook.contacts.services import create_contact, delete_phone_number, get_contact, update_contact


class AddContactView(View):
    def get(self, request):
        country_codes = list_country_codes()
        return render(request, "contacts/add_contact.html", {"country_codes": country_codes})

    def post(self, request):
        name = request.POST["name"]
        numbers = request.POST.getlist("numbers[]")
        codes = request.POST.getlist("codes[]")

        try:
            create_contact(name=name, numbers=numbers, codes=codes)
        except ValueError as e:
            country_codes = list_country_codes()
            return render(request, "contacts/add_contact.html", {"country_codes": country_codes, "error": str(e)})

        return redirect("contacts:contact_list")


class ContactListView(ListView):
    queryset = list_contacts()
    context_object_name = "contacts"
    paginate_by = 2
    template_name = "contacts/contact_list.html"


class ContactDetailView(View):
    def get(self, request, pk):
        try:
            contact = get_contact(pk=pk)
        except Http404:
            return render(request, "404.html", status=404)
        return render(request, "contacts/contact_detail.html", {"contact": contact})


class DeleteContactView(View):
    def get(self, request, pk):
        contact = get_contact(pk=pk)
        if contact is None:
            return render(request, "404.html", status=404)

        contact.delete()
        return redirect("contacts:contact_list")


class EditContactView(View):
    def get(self, request, pk):
        contact = get_contact(pk=pk)
        country_codes = list_country_codes()
        return render(request, "contacts/edit_contact.html", {"contact": contact, "country_codes": country_codes})

    def post(self, request, pk):
        id = request.POST["contact_id"]
        name = request.POST["name"]
        numbers = request.POST.getlist("numbers[]")
        codes = request.POST.getlist("codes[]")
        update_contact(id=id, name=name, numbers=numbers, codes=codes)
        return redirect("contacts:contact_list")


class DeletePhoneView(View):
    def get(self, request, pk):
        contact = delete_phone_number(pk=pk)
        return redirect("contacts:contact_detail", pk=contact.pk)

phonebook/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

phonebook/templates/contacts/add_contact.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-1">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="post" class="form">
          {% csrf_token %}
          <div class="form-group">
            <label for="name">Name:</label>
            <input id="name" type="text" name="name" class="form-control" required />
          </div>
          <div id="phone-numbers">
            <div class="form-group phone-number">
              <div class="row">
                <div class="col-md-4">
                  <label for="codes">Country Code:</label>
                  <select id="codes" name="codes[]" class="form-control" required>
                    {% for country_code in country_codes %}
                      <option value="{{ country_code.code }}">{{ country_code.name }} {{ country_code.code }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-md-8">
                  <label for="numbers">Number:</label>
                  <input id="numbers"
                         type="number"
                         name="numbers[]"
                         class="form-control"
                         required />
                </div>
              </div>
            </div>
          </div>
          <button type="submit" class="btn btn-primary mt-1">Add Contact</button>
          <button type="button" id="add-phone-number" class="btn btn-secondary mt-1">Add Phone Number</button>
        </form>
        {% if error %}<div class="alert alert-danger mt-1">{{ error }}</div>{% endif %}
      </div>
    </div>
  </div>
  <script>
    document.getElementById('add-phone-number').addEventListener('click', function() {
      var phoneNumbers = document.getElementById('phone-numbers');
      var newPhoneNumber = phoneNumbers.getElementsByClassName('phone-number')[0].cloneNode(true);
      phoneNumbers.appendChild(newPhoneNumber);
    });
  </script>
{% endblock content %}

phonebook/templates/contacts/contact_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h1 class="text-center">{{ contact.name }}</h1>
        <ul class="list-group">
          {% for number in contact.phone_numbers.all %}
            <li class="list-group-item text-center fs-3">
              {{ number.country_code.code }} {{ number.number }}
              <a href="{% url 'contacts:delete_phone_number' number.id %}"
                 class="btn btn-danger btn-sm">Delete</a>
            </li>
          {% endfor %}
        </ul>
        <div class="text-center mt-1">
          <a href="{% url 'contacts:edit_contact' contact.id %}"
             class="btn btn-primary">Edit</a>
          <a href="{% url 'contacts:delete_contact' contact.id %}"
             class="btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

phonebook/templates/contacts/contact_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        {% if contacts %}
          <ul class="list-group">
            {% for contact in contacts %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="fs-5 text-decoration-none col-3"
                   href="{% url 'contacts:contact_detail' contact.id %}">{{ contact.name }}</a>
                <span class="text-muted col-4">{{ contact.created_at }}</span>
                <a class="btn btn-danger col-2"
                   href="{% url 'contacts:delete_contact' contact.id %}">Delete</a>
              </li>
            {% endfor %}
          </ul>
          {% include "pagination.html" with page=page_obj %}
        {% else %}
          <p class="fs-4 text-center">There are no contacts.</p>
          <div class="text-center">
            <a class="btn btn-primary" href="{% url 'contacts:add_contact' %}">Add Contact</a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

phonebook/templates/contacts/edit_contact.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-1">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="post" class="form">
          {% csrf_token %}
          <div class="form-group">
            <label for="name">Name:</label>
            <input id="name"
                   type="text"
                   name="name"
                   class="form-control"
                   value="{{ contact.name }}"
                   required />
          </div>
          <input id="contact_id"
                 type="hidden"
                 name="contact_id"
                 value="{{ contact.id }}" />
          {% for phone_number in contact.phone_numbers.all %}
            <div id="phone-numbers">
              <div class="form-group phone-number">
                <div class="row">
                  <div class="col-md-4">
                    <label for="codes">Country Code:</label>
                    <select id="codes"
                            name="codes[]"
                            class="form-control"
                            value="{{ phone_number.country_code.name }} {{ phone_number.country_code.code }}"
                            required>
                      {% for country_code in country_codes %}
                        <option value="{{ country_code.code }}">{{ country_code.name }} {{ country_code.code }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-md-8">
                    <label for="numbers">Number:</label>
                    <input id="numbers"
                           type="number"
                           name="numbers[]"
                           class="form-control"
                           value="{{ phone_number.number }}"
                           required />
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-success mt-1">Save</button>
          <button type="button" id="add-phone-number" class="btn btn-secondary mt-1">Add Phone Number</button>
        </form>
        {% if error %}<div class="alert alert-danger mt-1">{{ error }}</div>{% endif %}
      </div>
    </div>
  </div>
  <script>
    document.getElementById('add-phone-number').addEventListener('click', function() {
      var phoneNumbers = document.getElementById('phone-numbers');
      var newPhoneNumber = phoneNumbers.getElementsByClassName('phone-number')[0].cloneNode(true);
      phoneNumbers.appendChild(newPhoneNumber);
    });
  </script>
{% endblock content %}